---
title: "Blood Panel Metrics App"
author: "Anthony Acaldo"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## <span style="color:blue">Introduction: Addressing a Critical Need in Healthcare</span>


Iron metabolism is a cornerstone of human health, influencing everything from oxygen transport to cognitive function. Abnormal iron levels are implicated in conditions like anemia, hemochromatosis, and even neurological disorders, making accurate interpretation of iron-related biomarkers essential. 

## Interpreting Iron Related Biomarkers

For healthcare providers, researchers, and patients, understanding biomarkers such as serum iron, ferritin, transferrin saturation (TSAT), and total iron-binding capacity (TIBC) can be complex due to varying clinical ranges and nutritional implications. 

## Tech Stack 

Our Blood Panel Metrics App, built using R Shiny, bridges this gap by offering an interactive, user-friendly platform to explore these biomarkers. This app empowers users to visualize biomarker values, understand clinical ranges, and access tailored nutritional guidance, making it an invaluable tool in clinical practice, research, and patient education—particularly in fields like neuroimaging where iron dysregulation is increasingly studied.

## Screenshot

this is for a screen




